#!/usr/bin/env python3
"""
Corpus C: the canonical reproducible natural corpus for RUM trigram
benchmarks.

Input is one raw mbox of a pgsql-hackers month.  Every message is
transformed by fixed rules into ~1KB search documents, and *all* chunks
are kept: the historical 10021 was an artifact of a lost parser, not a
property of the workload, so nothing here is tuned to reproduce it.

Determinism: the transformation is a pure function of the input bytes.
No sampling, no randomness, no seed.  The compact variant (--stratified)
selects chunks round-robin across messages, so a smaller set still spans
every message rather than the first few.

Output:
    <out>.csv          msg_no, chunk_no, subject, body, id
    <out>.manifest.md  rules, checksums, coverage, distribution

Usage:
    python3 generate_natural_corpus.py --mbox FILE --out corpus_c
    python3 generate_natural_corpus.py --mbox FILE --out corpus_c10k \\
            --stratified 10000
"""
import argparse
import csv
import hashlib
import re
import sys
from collections import Counter

CHUNK_BYTES = 1000
MIN_CHUNK_BYTES = 200

# Lines dropped before chunking.  Diff and quotation bodies are removed
# because they duplicate text across messages and distort trigram
# frequencies, which is what the benchmarks measure.
DROP_PREFIXES = ("+", "-", ">", "diff ", "index ", "@@", "--- ", "+++ ")


def split_messages(raw):
    """Split an mbox on From_ lines.  Kept deliberately simple and
    documented rather than clever: the rule is what must be stable."""
    parts = re.split(r"\nFrom -? ?\S+ ", raw)
    return [p for p in parts if p.strip()]


def decode_body(message):
    """Header/body split, then normalize line endings.  No MIME walking:
    the corpus is plain text by construction of the rules below."""
    head, _, body = message.partition("\n\n")
    subject = ""
    m = re.search(r"^Subject:\s*(.*)$", head, re.M)
    if m:
        subject = m.group(1).strip()[:200]
    body = body.replace("\r\n", "\n").replace("\r", "\n")
    return subject, body


def clean_lines(body):
    kept = [ln for ln in body.split("\n")
            if not ln.startswith(DROP_PREFIXES)]
    return " ".join(" ".join(kept).split())


def chunks_of(text):
    out = []
    for i in range(0, len(text), CHUNK_BYTES):
        c = text[i:i + CHUNK_BYTES]
        if len(c) >= MIN_CHUNK_BYTES:
            out.append(c)
    return out


def build(raw):
    docs = []          # (msg_no, chunk_no, subject, body)
    per_message = {}
    for mno, msg in enumerate(split_messages(raw), start=1):
        subject, body = decode_body(msg)
        cs = chunks_of(clean_lines(body))
        per_message[mno] = len(cs)
        for cno, c in enumerate(cs):
            docs.append((mno, cno, subject, c))
    return docs, per_message


def stratify(docs, limit):
    """Round-robin across messages: take chunk 0 of every message, then
    chunk 1 of every message, and so on.  Coverage is maximal for any
    limit, and the result is a deterministic function of the input."""
    by_msg = {}
    for d in docs:
        by_msg.setdefault(d[0], []).append(d)
    out = []
    depth = 0
    while len(out) < limit:
        progressed = False
        for mno in sorted(by_msg):
            if depth < len(by_msg[mno]):
                out.append(by_msg[mno][depth])
                progressed = True
                if len(out) >= limit:
                    break
        if not progressed:
            break
        depth += 1
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mbox", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--stratified", type=int, default=0,
                    help="emit at most N chunks, round-robin across messages")
    args = ap.parse_args()

    data = open(args.mbox, "rb").read()
    in_sha = hashlib.sha256(data).hexdigest()
    raw = data.decode("utf-8", "replace")

    docs, per_message = build(raw)
    total_messages = len(per_message)
    total_chunks = len(docs)

    if args.stratified:
        docs = stratify(docs, args.stratified)

    covered = len({d[0] for d in docs})
    csv_path = args.out + ".csv"
    with open(csv_path, "w", newline="") as f:
        w = csv.writer(f)
        for i, (mno, cno, subj, body) in enumerate(docs, start=1):
            w.writerow([mno, cno, subj, body, i])
    out_sha = hashlib.sha256(open(csv_path, "rb").read()).hexdigest()

    dist = Counter(per_message.values())
    lens = sorted(len(d[3]) for d in docs)
    manifest = args.out + ".manifest.md"
    with open(manifest, "w") as f:
        f.write("# Corpus manifest: %s\n\n" % args.out)
        f.write("Generated by `generate_natural_corpus.py`, a pure function "
                "of the input bytes: no sampling, no randomness, no seed.\n\n")
        f.write("## Checksums\n\n")
        f.write("    input  sha256  %s\n" % in_sha)
        f.write("    output sha256  %s\n\n" % out_sha)
        f.write("## Rules\n\n")
        f.write("    message split      /\\nFrom -? ?\\S+ /\n")
        f.write("    header/body split  first blank line\n")
        f.write("    line endings       CRLF and CR normalized to LF\n")
        f.write("    dropped lines      prefixes %s\n" % (DROP_PREFIXES,))
        f.write("    whitespace         collapsed to single spaces\n")
        f.write("    chunk size         %d bytes\n" % CHUNK_BYTES)
        f.write("    minimum chunk      %d bytes (shorter tails dropped)\n"
                % MIN_CHUNK_BYTES)
        f.write("    subject            first Subject: header, 200 chars\n")
        f.write("    selection          %s\n\n" %
                ("all chunks" if not args.stratified else
                 "round-robin across messages, limit %d" % args.stratified))
        f.write("## Coverage\n\n")
        f.write("    messages in mbox        %d\n" % total_messages)
        f.write("    messages represented    %d (%.1f%%)\n" %
                (covered, 100.0 * covered / total_messages))
        f.write("    chunks produced total   %d\n" % total_chunks)
        f.write("    chunks emitted          %d\n\n" % len(docs))
        f.write("## Chunk-count distribution per message\n\n")
        f.write("    chunks/message : messages\n")
        for k in sorted(dist)[:12]:
            f.write("    %14d : %d\n" % (k, dist[k]))
        if len(dist) > 12:
            f.write("    (%d further buckets, max %d chunks in one message)\n"
                    % (len(dist) - 12, max(dist)))
        f.write("\n## Emitted document length in bytes\n\n")
        if lens:
            f.write("    min %d  p50 %d  p95 %d  max %d\n" %
                    (lens[0], lens[len(lens) // 2],
                     lens[int(len(lens) * 0.95)], lens[-1]))
    print("wrote %s (%d documents, %d/%d messages) and %s"
          % (csv_path, len(docs), covered, total_messages, manifest))


if __name__ == "__main__":
    sys.exit(main())
